config/routes.rb
Rails.application.routes.draw do

  post 'contactus' => 'static_pages#contactus'

  post  'language' => 'sessions#create'

  devise_for :users
  get 'registermanagement' => 'admins#registermanagement'
  get 'filemanagement' => 'admins#filemanagement'

  root 'static_pages#home'

  get  'info'      => 'static_pages#info'
  get  'declare'   => 'static_pages#declare'
  get  'search'    => 'static_pages#search'
  get  'form'      => 'static_pages#form'

  get 'prohibit' => 'registers#prohibit'

  get 'allpayform' => 'static_pages#allpayform'

  post 'notify', to: 'static_pages#notify', as: 'notify'

  get "static_pages/check_email", :controller => "static_pages", :action => "check_email"
  resources :transactions, only: :index
  resources :registers
  resources :tdmfiles,     only: [:create,:destroy]
  resources :works,        only: [:index,:show,:create,:destroy]
  resources :displayingwork, only: :update
  resources :banners, only: [:index,:update]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  skip_before_action :verify_authenticity_token, only: [:notify]
  # before_action :check_language, except: [:notify]
  
  def home
    @works=Displayingwork.first.works.all
    @displayingwork=Displayingwork.first
    @work1=Work.find_by(id:@displayingwork.col1)
    @work2=Work.find_by(id:@displayingwork.col2)
    @work3=Work.find_by(id:@displayingwork.col3)
    @work4=Work.find_by(id:@displayingwork.col4)
    @work5=Work.find_by(id:@displayingwork.col5)
    @work6=Work.find_by(id:@displayingwork.col6)
    @banners=Banner.all.order(:id)
  end

  def info
  end

  def notify
    if mac_value_ok?
      trans=Transaction.find_by!(trade_number: params[:MerchantTradeNo])
      trans.update!(params: request.POST)
      register=Register.find_by(id:trans.register_id)
      if trans.params['RtnCode']=="1"
        if trans.params['TradeAmt']=="500"
          Mail.deliver(from:'LINE DDD',to:register.email,subject:"繳費成功-LINE DDD 3D列印競賽",body:"您已於歐付寶成功支付LINE DDD主辦3D列印競賽報名費用")
          register.update_attributes(paystatus:3)
        else
          Mail.deliver(from:'LINE DDD',to:register.email,subject:"繳費金額有誤-LINE DDD 3D列印競賽",body:"您於歐付寶支付之金額與LINE DDD主辦3D列印競賽報名費有誤差，請與主辦方聯絡")
          register.update_attributes(paystatus:1)
        end
      end
    end
  end

  def contactus
    if params[:email]!="" && params[:subject]!="" && params[:name]!="" && params[:message]!=""
      Mail.deliver(from:params[:email],to:"s5355049@gmail.com",subject:params[:subject],body:params[:name]+params[:message])
    end
  end

  def check_email
    @register = Register.find_by_email(params[:email])

    respond_to do |format|
      format.json { render :json => !@register }
    end
  end

  def allpayform
    register=Register.find_by(email:params[:register])
    @params={}
    @params['ChoosePayment']="Credit"
    @params['ClientBackURL']="http://tdpcontest.herokuapp.com/registers?utf8=%E2%9C%93&search="+CGI::escape(register.email)+"&n="+CGI::escape(register.name)
    @params['ItemName']="LINE DDD 3D列印創新競賽"
    @params['MerchantID']="2000132"
    # ENV['MERCHANT_ID']
    @params['MerchantTradeDate']=register.transactions.last.created_at.strftime("%Y/%m/%d %T")
    @params['MerchantTradeNo']=register.transactions.create!.trade_number
    @params['PaymentType']="aio"
    @params['ReturnURL']="http://tdpcontest.herokuapp.com/notify"
    @params['TotalAmount']="500"
    @params['TradeDesc']="報名費500"
    param=create_mac
    @params['CheckMacValue']=param
  end

  private

    def mac_value_ok?
      params_copy = params.dup

      params_to_go = params_copy.except(:CheckMacValue, :action, :controller)

      raw_data = params_to_go.sort.map do |x,y|
        "#{x}=#{y}"
      end.join('&')

      hash_raw_data = "HashKey=5294y06JbISpM5x9&#{raw_data}&HashIV=v77hoKGq4kWxNNIS"
      # hash_raw_data = "HashKey=#{EzAllpay.hash_key}&#{raw_data}&HashIV=#{EzAllpay.hash_iv}"

      url_encode_data = (CGI::escape(hash_raw_data)).downcase

      my_mac = Digest::MD5.hexdigest(url_encode_data)

      params_no_mac = params[:CheckMacValue]

      if my_mac ==params_no_mac.to_s.downcase
        return true
      else
        return false
      end
    end

    def create_mac
      params_copy = @params.dup

      raw_data = params_copy.sort.map do |x,y|
        "#{x}=#{y}"
      end.join('&')

      hash_raw_data = "HashKey=5294y06JbISpM5x9&#{raw_data}&HashIV=v77hoKGq4kWxNNIS"
      # hash_raw_data = "HashKey=#{EzAllpay.hash_key}&#{raw_data}&HashIV=#{EzAllpay.hash_iv}"

      url_encode_data = (CGI::escape(hash_raw_data)).downcase

      my_mac = Digest::MD5.hexdigest(url_encode_data).upcase
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def isHome?
    request.url==root_url
  end
end

app/views/static_pages/allpayform.html.erb
<form action="https://payment-stage.allpay.com.tw/Cashier/AioCheckOut" method="post" style="display:none">
  <% @params.each do |key,value| %>
    <input type="text" name="<%= key %>" value="<%= value %>">
  <% end %>
  <input type="submit">
</form>
<script>document.forms[0].submit()</script>

app/views/static_pages/form.html.erb
<div class="container form">
  <h3 class="center"><%= t("線上報名") %></h3>
  <hr class="hr">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">

      <%= form_tag new_register_path,method: :get, :id => 'new_register' do %>
        <div style="display:inline-block;">
          <%= label :n, t("報名者姓名") %>
        </div>
        <div class="error">
          <p class="namehide hidden nameok">&nbsp;&nbsp;<i class="fa fa-check"></i></p>
          <p class="namehide hidden nameblank"><strong>&nbsp;&nbsp;<%= t("請輸入姓名") %></strong></p>
        </div>
        <%= text_field_tag :n, params[:n], placeholder: t("姓名"), class: 'form-control' %>
        <div style="display:inline-block;">
          <%= label :email, "E-mail" %>
        </div>
        <div class="error">
          <p class="emailhide hidden emailok">&nbsp;&nbsp;<i class="fa fa-check"></i></p>
          <p class="emailhide hidden emailblank">&nbsp;&nbsp;<%= t("請輸入E-mail") %></p>
          <p class="emailhide hidden emailmatch">&nbsp;&nbsp;<%= t("請輸入一個有效的E-mail") %></p>
          <p class="emailhide hidden emailchecking">&nbsp;&nbsp;<img src="/assets/loader.gif" /><%= t("驗證中") %>...</p>
          <p class="emailhide hidden emailused">&nbsp;&nbsp;<%= t("此E-mail已報名") %></p>
        </div>
        <%= text_field_tag :email, params[:email], placeholder:"E-mail", class: 'form-control' %>
        <br>
        <div class="center">
          <%=submit_tag t("送出"), name: nil, class: "btn btn-lg btn-success" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    if($('#email').val()!=""){$('#email').val("")}
    if($('#n').val()!=""){checkName()}
  })
  $('#n').each(function(){
    var elem = $(this)
    var nowtime=0
    var oldtime=0
    elem.data('oldval',elem.val())
    elem.bind("propertychange change click keyup input paste", function(event){
      if(elem.data('oldval')!=elem.val()){
        nowtime++
        $('.namehide').addClass('hidden')
        elem.data('oldval',elem.val())
        setTimeout(function(){
          oldtime++
          if(nowtime==oldtime){checkName()}
        },1000)
      }
    })
  })
  $('#email').each(function(){
    var elem = $(this)
    var nowtime=0
    var oldtime=0
    elem.data('oldval',elem.val())
    elem.bind("propertychange change click keyup input paste", function(event){
      if(elem.data('oldval')!=elem.val()){
        nowemail=$('#email').val()
        nowtime++
        $('.emailhide').addClass('hidden')
        elem.data('oldval',elem.val())
        setTimeout(function(){
          oldtime++
          if(nowtime==oldtime){
            if(checkEmail()==true){
              $('.emailchecking').removeClass('hidden')
              $.getJSON("/static_pages/check_email?email="+nowemail,function(result){
                if(nowtime==oldtime){
                  if(result==false){$('.emailused').removeClass('hidden')}
                  else{$('.emailok').removeClass('hidden')}
                  $('.emailchecking').addClass('hidden')
                }
              })
            }
          }
        },1000)
      }
    })
  })
  $('#new_register').submit(function(){
    checkName()
    checkEmail()
    if(!$('.nameok').hasClass("hidden") && !$('.emailok').hasClass("hidden")){return true}
    else{return false}
  })
  function checkName(){
    if($('#n').val()==""){$('.nameblank').removeClass('hidden')}
    else{$('.nameok').removeClass('hidden')}
  }
  function checkEmail(){
    val=$('#email').val()
    if(val==""){$('.emailblank').removeClass('hidden')}
    else if(validEmail(val)==false){$('.emailmatch').removeClass('hidden')}
    else{return true}
  }
  function usedEmail(){
    $('.emailchecking').removeClass('hidden')
    $.getJSON("/static_pages/check_email?email="+$('#email').val(),function(result){
      if(result!=false){
        $('.emailok').removeClass("hidden")
        $('.emailchecking').addClass("hidden")
      }
    })
  }
  function validEmail(value){
    var rule = new RegExp(/^[+a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{1,10}$/i)
    return rule.test(value)
  }
</script>

app/views/static_pages/info.html.erb
<h1>StaticPages#info</h1>
<p>Find me in app/views/static_pages/info.html.erb</p>

  <img src="/images/logo.jpg" alt="rss feed" />

app/views/static_pages/search.html.erb
<div class="container search">
  <h3 class="center"><%= t("報名查詢") %></h3>
  <hr class="hr">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">

      <%= form_tag registers_path,method: :get do %>
        <%= label :search,t("請輸入E-mail") %>
        <%= text_field_tag :search, params[:search], placeholder:"E-mail", class: 'form-control' %>
        <%= label :n,t("請輸入姓名") %>
        <%= text_field_tag :n, params[:n], placeholder: t("姓名"), class: 'form-control' %>
        <br>
        <div class="center">
          <%=submit_tag t("查詢"), name: nil, class: "btn btn-lg btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>