config/routes.rb
Rails.application.routes.draw do

  post 'contactus' => 'static_pages#contactus'

  post  'language' => 'sessions#create'

  devise_for :users
  get 'registermanagement' => 'admins#registermanagement'
  get 'filemanagement' => 'admins#filemanagement'

  root 'static_pages#home'

  get  'info'      => 'static_pages#info'
  get  'declare'   => 'static_pages#declare'
  get  'search'    => 'static_pages#search'
  get  'form'      => 'static_pages#form'

  get 'prohibit' => 'registers#prohibit'

  get 'allpayform' => 'static_pages#allpayform'

  post 'notify', to: 'static_pages#notify', as: 'notify'

  get "static_pages/check_email", :controller => "static_pages", :action => "check_email"
  resources :transactions, only: :index
  resources :registers
  resources :tdmfiles,     only: [:create,:destroy]
  resources :works,        only: [:index,:show,:create,:destroy]
  resources :displayingwork, only: :update
  resources :banners, only: [:index,:update]

end

app/models/register.rb
class Register < ActiveRecord::Base
  has_many :transactions, dependent: :destroy
  has_many :tdmfiles, dependent: :destroy
  default_scope -> {order(updated_at: :desc)}
  before_save { self.email = email.downcase }
  before_create :generate_no
  validates :name,  presence: { message: "請填寫姓名" }, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  def generate_no
    loop do
      self.merchant_trade_no = "TDPC#{self.created_at.strftime("%Y%m%d")}#{SecureRandom.hex(3).upcase}"
      break unless Register.where(merchant_trade_no: self.merchant_trade_no).first
    end
  end

  def params
    transaction = transactions.find_by("params -> 'RtnCode' = '1' OR params -> 'TradeStatus' = '1'")
    if transaction.present?
      return transaction.params
    end
  end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController

  before_action :authenticate_user!, only:[:prohibit]
  # before_action :check_language

  def index
    if params[:search] == "" || params[:n] == ""
      redirect_to search_path
      flash[:danger]="請輸入完整資料"
    else
      if Register.find_by(email: params[:search],name: params[:n]) == nil
        redirect_to search_path
        flash[:danger]="查無此筆資料"
      else
        @register = Register.find_by(email: params[:search],name: params[:n])
        @transaction = @register.transactions.find_by("params -> 'RtnCode' = '1' OR params -> 'TradeStatus' = '1'")
        if @register.paystatus==3 && @transaction.params['PaymentType']=="Credit_CreditCard"
          # @params = {}
          # @params['MerchantID']=ENV['MERCHANT_ID']
          # @params['MerchantTradeNo']=@transaction.params["MerchantTradeNo"]
          # @params['TradeNo']=@transaction.params["TradeNo"]
          # @params['Action']="R"
          # @params['TotalAmount']=@transaction.params["TradeAmt"]
          # param=create_mac
          # @params['CheckMacValue']=param
          @tdmfile=@register.tdmfiles.build
        end
      end
    end
  end

  def new
    @register = Register.new(name: params[:n],email: params[:email])
  end

  def create
    @register = Register.new(register_params)
    if @register.save
      @register.transactions.create
      # Mail.deliver(from:'LINE DDD',to:@register.email,subject:"報名成功-LINE DDD 3D列印競賽",body:"您已成功報名LINE DDD主辦3D列印競賽")
      render 'confirm'
    else
      render 'new'
    end
  end

  def prohibit
    register=Register.find_by(email:params[:email])
    if register.prohibit==true
      register.update_attributes(prohibit:false)
    else
      register.update_attributes(prohibit:true)
    end
    redirect_to registermanagement_path
  end

  def confirm
    if @register==nil
      redirect_to root_url
    end
  end

  private

    def picture_params
      params.require(:register).permit(:picture)
    end

    def register_params
      params.require(:register).permit(:name, :email)
    end

    def create_mac
      params_copy = @params.dup

      raw_data = params_copy.sort.map do |x,y|
        "#{x}=#{y}"
      end.join('&')

      hash_raw_data = "HashKey=#{EzAllpay.hash_key}&#{raw_data}&HashIV=#{EzAllpay.hash_iv}"

      url_encode_data = (CGI::escape(hash_raw_data)).downcase

      my_mac = Digest::MD5.hexdigest(url_encode_data).upcase
    end
end

app/helpers/registers_helper.rb
module RegistersHelper

  def hasTdmfile?(register)
    register.tdmfiles.count==0
  end
end

app/views/registers/confirm.html.erb
<div class="container confirm center">
  <h3><%= t("報名成功！") %></h3>
  <hr class="hr">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">

      <tbody>
        <table class="table table-hover">
          <tr>
            <td><%= t("報名者姓名") %></td>
            <td><%= @register.name %></td>
          </tr>
          <tr>
            <td>E-mail</td>
            <td><%= @register.email %></td>
          </tr>
        </table>
      </tbody>

      <div>
        <%= form_tag allpayform_path, method: :get do %>
          <%= hidden_field_tag :register, params[:register],value: @register.email %>
          <%=submit_tag t("付款"), name: nil, class: "btn btn-lg btn-success" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/registers/index.html.erb
<div class="container searchindex center">
  <h3><%= t("報名編號") %><%= @register.merchant_trade_no %></h3>
  <hr class="hr">
  <div class="register_holder">
    <% if @register.prohibit==true %>
      <p class="bg-danger"><%= t("已封鎖") %></p>
    <% else %>
      <% if @register.paystatus==3 %>
        <p class="bg-success"><%= t("已付款") %></p>
      <% elsif @register.paystatus==1 %>
        <p class="bg-danger"><%= t("帳單金額錯誤") %></p>
      <% else %>
        <p class="bg-danger"><%= t("尚未付款") %></p>
      <% end %>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <tbody>
        <table class="table table-hover">
          <tr>
            <td><%= t("報名者姓名") %></td>
            <td><%= @register.name %></td>
          </tr>
          <tr>
            <td>E-mail</td>
            <td><%= @register.email %></td>
          </tr>
          <% if @register.paystatus==1 || @register.paystatus==3 %>
            <tr>
              <td><%= t("付款金額") %></td>
              <td><%= @transaction.params["TradeAmt"] %></td>
            </tr>
            <tr>
              <td><%= t("付款日期") %></td>
              <td><%= @transaction.params["PaymentDate"] %></td>
            </tr>
            <tr>
              <td><%= t("付款方式") %></td>
              <td><%= @transaction.params["PaymentType"] %></td>
            </tr>
          <% end %>
        </table>
      </tbody>
      
    </div>
  </div>

  <% if @register.prohibit==false %>
    <% if @register.paystatus==2 %>
      <div>
        <%= form_tag allpayform_path, method: :get do %>
          <%= hidden_field_tag :register, params[:register],value: @register.email %>
          <%=submit_tag t("付款"), name: nil, class: "btn btn-lg btn-success" %>
        <% end %>
      </div>
    <% elsif @register.paystatus==3 %>
      <% if hasTdmfile?(@register) %>
        <div style="padding: 50px 0;">
          <h3><%= t("檔案上傳說明") %><i class="fa fa-file"></i></h3>
          <br>
          <h4><%= t("3D列印設計圖上傳限IGS檔") %></h4>
          <h4><%= t("請以作品名稱命名欲上傳之3D列印設計圖檔") %>  <small><%= t("例") %>：”<%= t("恐龍骨架模型") %>.igs“</small></h4>
          <h4><%= t("並至少上傳最少一張，最多三張之該模型照片") %></h4>
        </div>
        <%= form_for(@tdmfile, html: { multipart: true }) do |f| %>
          <input type="hidden" name="email" id="email" value="<%= @register.email %>" />
          <input type="hidden" name="name" id="name" value="<%= @register.name %>" />
          <div class="row igs_holder">
            <div class="col-xs-12 col-md-12">
              <%= f.file_field :igsfile, "data-buttonText":t("選擇檔案"), "data-placeholder":'IGS', class:'filestyle', style:"display:inline-block", accept: '.igs' %>
            </div>
            <div class="error_holder">
              <p class="igserror hidden igstype"><%= t("檔案格式錯誤") %></p>
              <p class="igserror hidden igssize"><%= t("檔案大小超過5MB，請選擇更小的檔案") %></p>
            </div>
          </div>
          <div class="row picture_holder">
            <% 3.times do |n| %>
              <div class="col-xs-4 col-md-4">
                <div id="picture<%= n+1 %>Preview" class="picturePreview">
                  <div class="delete_holder">
                    <div id="picture<%= n+1 %>" class="deleteButton">×</div>
                  </div>
                </div>
                <div style="display: inline-block;">
                  <%= f.file_field :picture1, id:"picture#{n+1}file", class:"filestyle uploadFile", name:"tdmfile[picture#{n+1}]", "data-input":false, "data-badge":false, "data-buttonText":t("選擇圖片"), "data-iconName":'glyphicon glyphicon-camera', accept: 'image/jpeg,image/png' %>
                </div>
                <div style="position: absolute;right:30%;">
                  <p class="pictureerror hidden picture<%= n+1 %>type"><%= t("檔案格式錯誤") %></p>
                </div>
                <div style="position: absolute;">
                  <p class="pictureerror hidden picture<%= n+1 %>size"><%= t("檔案大小超過800KB，請選擇更小的檔案") %></p>
                </div>
              </div>
            <% end %>
          </div>
          <div>
            <%= f.submit t("確定並上傳"), class: "btn btn-primary btn-lg", id: "filesubmit" %>
          </div>
        <% end %>
        
        <script>
          function pictureDelete(id){
            $('#'+id+'Preview').css("background-image","url()");
            $('#'+id+"file").filestyle('clear');
            $('#'+id).css('display','none');
          }
          $('.deleteButton').click(function(){
            var id=$(this).attr('id')
            pictureDelete(id)
          })
          $('#tdmfile_igsfile').on("change",function(){
            if($(this).val()==""){
              $(this).filestyle('clear');
            }
          })
          $('.uploadFile').on("change",function(){
            var size_in_megabytes = this.files[0].size/1024/1024;
            var n;
            if ($(this).is("#picture1file")){n="picture1"}
            if ($(this).is("#picture2file")){n="picture2"}
            if ($(this).is("#picture3file")){n="picture3"}
            if($('#'+n+'file').val()==""){
              pictureDelete(n)
            }
            else{
              if(size_in_megabytes>0.8){
                pictureDelete(n)
                $('.'+n+'type').addClass('hidden');
                $('.'+n+'size').removeClass('hidden');
              }
            }
          })
          checkFileSize($('#tdmfile_igsfile'))
          checkFileSize($('#picture1file'))
          checkFileSize($('#picture2file'))
          checkFileSize($('#picture3file'))
          $('#new_tdmfile').submit(function(){
            if($('#tdmfile_igsfile').val()!=""){
              if(($('#picture1file').val()!="") || ($('#picture2file').val()!="") || ($('#picture3file').val()!="")){return true}
            }
            alert('<%= t("上傳的檔案不完整") %>');
            return false
          })
          function checkFileSize(file){
            file.bind('change', function(){
              var size_in_megabytes = this.files[0].size/1024/1024;
              var ext=file.val().split('.').pop().toLowerCase();
              if(file.is('#tdmfile_igsfile')){
                if($.inArray(ext,['igs'])==-1){
                  $('.igstype').removeClass('hidden');
                  $('#tdmfile_igsfile').filestyle('clear');
                  resetFormElement($(this))
                }
                else{
                  if (size_in_megabytes>5){
                    $('.igssize').removeClass('hidden');
                    $('#tdmfile_igsfile').filestyle('clear');
                    resetFormElement($(this))
                  }
                  else{
                    $('.igstype').addClass('hidden');
                    $('.igssize').addClass('hidden');
                  }
                }
              }
              else{
                var n;
                if (file.is("#picture1file")){n="picture1"}
                if (file.is("#picture2file")){n="picture2"}
                if (file.is("#picture3file")){n="picture3"}
                if($.inArray(ext,['png','jpg','jpeg'])==-1){
                  $('.'+n+'type').removeClass('hidden');
                  $('.'+n+'size').addClass('hidden');
                  pictureDelete(n)
                  resetFormElement($(this))
                }
                else{
                  if(size_in_megabytes>0.8){
                    resetFormElement($(this))
                  }
                  else{
                    $('.'+n+'type').addClass('hidden');
                    $('.'+n+'size').addClass('hidden');
                    $('#'+n).css('display','inline-block');
                    var files = !!this.files ? this.files : [];
                    if (!files.length || !window.FileReader) return;
                    if (/^image/.test( files[0].type)){
                      var reader = new FileReader();
                      reader.readAsDataURL(files[0]);
                      reader.onloadend = function(){
                        $("#"+n+"Preview").css("background-image", "url("+this.result+")");
                      }
                    }
                  }
                }
              }
            })
          }
          function resetFormElement(e){
            e.wrap('<form>').closest('form').get(0).reset();
            e.unwrap();
            e.stopPropagation();
            e.preventDefault();
          }
        </script>
      <% else %>
        <div style="padding: 20px 0;">
          <h3><%= t("上傳完成") %></h3>
          <% tdmfile=@register.tdmfiles.first %>
          <%= tdmfile.igsfile.to_s.rpartition("/").last %>
        </div>
        <% if tdmfile.picture1.url!=nil %>
          <div class="picturePreview" style="background-image: url('<%= @register.tdmfiles.first.picture1.url %>');"></div>
        <% end %>
        <% if tdmfile.picture2.url!=nil %>
          <div class="picturePreview" style="background-image: url('<%= @register.tdmfiles.first.picture2.url %>');"></div>
        <% end %>
        <% if tdmfile.picture3.url!=nil %>
          <div class="picturePreview" style="background-image: url('<%= @register.tdmfiles.first.picture3.url %>');"></div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/registers/new.html.erb
<div class="container new center">
  <h3><%= t("報名確認") %></h3>
  <hr class="hr">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">

      <tbody>
        <table class="table table-hover">
          <tr>
            <td><%= t("報名者姓名") %></td>
            <td><%= @register.name %></td>
          </tr>
          <tr>
            <td>E-mail</td>
            <td><%= @register.email %></td>
          </tr>
        </table>
      </tbody>

      <%= form_for(@register) do |f| %>
        <%= f.hidden_field :name, class: 'form-control' %>
        <%= f.hidden_field :email, class: 'form-control' %>
        <br>
        <div>
          <%= f.submit t("確認報名"), class: "btn btn-lg btn-success" %>
        </div>
      <% end %>

    </div>
  </div>
</div>