config/routes.rb
Rails.application.routes.draw do

  post 'contactus' => 'static_pages#contactus'

  post  'language' => 'sessions#create'

  devise_for :users
  get 'registermanagement' => 'admins#registermanagement'
  get 'filemanagement' => 'admins#filemanagement'

  root 'static_pages#home'

  get  'info'      => 'static_pages#info'
  get  'declare'   => 'static_pages#declare'
  get  'search'    => 'static_pages#search'
  get  'form'      => 'static_pages#form'

  get 'prohibit' => 'registers#prohibit'

  get 'allpayform' => 'static_pages#allpayform'

  post 'notify', to: 'static_pages#notify', as: 'notify'

  get "static_pages/check_email", :controller => "static_pages", :action => "check_email"
  resources :transactions, only: :index
  resources :registers
  resources :tdmfiles,     only: [:create,:destroy]
  resources :works,        only: [:index,:show,:create,:destroy]
  resources :displayingwork, only: :update
  resources :banners, only: [:index,:update]

end

app/models/banner.rb
class Banner < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/models/displayingwork.rb
class Displayingwork < ActiveRecord::Base
  has_many :works
end

app/models/register.rb
class Register < ActiveRecord::Base
  has_many :transactions, dependent: :destroy
  has_many :tdmfiles, dependent: :destroy
  default_scope -> {order(updated_at: :desc)}
  before_save { self.email = email.downcase }
  before_create :generate_no
  validates :name,  presence: { message: "請填寫姓名" }, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  def generate_no
    loop do
      self.merchant_trade_no = "TDPC#{self.created_at.strftime("%Y%m%d")}#{SecureRandom.hex(3).upcase}"
      break unless Register.where(merchant_trade_no: self.merchant_trade_no).first
    end
  end

  def params
    transaction = transactions.find_by("params -> 'RtnCode' = '1' OR params -> 'TradeStatus' = '1'")
    if transaction.present?
      return transaction.params
    end
  end
end

app/models/tdmfile.rb
class Tdmfile < ActiveRecord::Base
  belongs_to :register
  mount_uploader :igsfile, IgsUploader
  mount_uploader :picture1, PictureUploader
  mount_uploader :picture2, PictureUploader
  mount_uploader :picture3, PictureUploader
  validates :register_id, presence: true
  validates :igsfile, presence: true
  validate :file_size

  private

    def file_size
      if igsfile.size > 5.megabytes
        errors.add(:igsfile)
      end
      if picture1.size > 0.8.megabytes
        errors.add(:picture1)
      end
      if picture2.size > 0.8.megabytes
        errors.add(:picture2)
      end
      if picture3.size > 0.8.megabytes
        errors.add(:picture3)
      end
    end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :register
  after_initialize :generate_trade_number

  def to_param
    trade_number
  end

  private

    def generate_trade_number
      loop do
        self.trade_number = SecureRandom.hex(3).upcase
        break unless Transaction.where(trade_number: self.trade_number).first
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :displayingwork
  mount_uploader :picture, PictureUploader
  validates :picture, presence: true
  validates :name, presence: true
  validates :workname, presence: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  before_action :authenticate_user!

  def registermanagement
    order=params[:order]
    if order=="1"
      @registers=Register.all.order("name DESC")
      @nameorder=2
      @nametri=true
    elsif order=="2"
      @registers=Register.all.order("name ASC")
      @nameorder=1
      @nametri=true
    elsif order=="3"
      @registers=Register.all.order("email DESC")
      @emailorder=4
      @emailtri=true
    elsif order=="4"
      @registers=Register.all.order("email ASC")
      @emailorder=3
      @emailtri=true
    elsif order=="5"
      @registers=Register.all.order("paystatus DESC")
      @paidorder=6
      @paidtri=true
    elsif order=="6"
      @registers=Register.all.order("paystatus ASC")
      @paidorder=5
      @paidtri=true
    else
      @registers=Register.all
    end
    if @nametri==true
      @emailtri=false
      @paidtri=false
    elsif @emailtri==true
      @nametri=false
      @paidtri=false
    elsif @paidtri==true
      @nametri=false
      @emailtri=false
    end
    @paidamount=0
    @todayregister=0
    @registers.all.each do |register|
      if register.created_at.strftime("%d")==Time.now.strftime("%d")
        @todayregister+=1
      end
    end
    @unpaidamount=0
    @erroramount=0
    @errprprofit=0
    @effectiveprofit=0
    @prohibitamount=0
    @registers.each do |register|
      if register.prohibit==true
        @prohibitamount+=1
      end
      if register.paystatus==3
        @paidamount+=1
        transaction=register.transactions.find_by("params -> 'RtnCode' = '1' OR params -> 'TradeStatus' = '1'")
        @effectiveprofit=@effectiveprofit+transaction.params['TradeAmt'].to_i
      elsif register.paystatus==1
        @paidamount+=1
        @erroramount+=1
        transaction=register.transactions.find_by("params -> 'RtnCode' = '1' OR params -> 'TradeStatus' = '1'")
        @errprprofit=@errprprofit+transaction.params['TradeAmt'].to_i
      else
        @unpaidamount+=1
      end
    end
  end

  def filemanagement
    @tdmfiles=Tdmfile.all
    @tdmfilecount=0;
    @tdmfiles.each do |tdmfile|
      if Register.find_by(id:tdmfile.register_id).prohibit==false
        @tdmfilecount+=1;
      end
    end
  end
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController

  before_action :authenticate_user!

  def index
    @banners=Banner.all.order(:id)
  end

  def update
    banner=Banner.find(params[:id])
    banner.update_attributes(banner_params)
    redirect_to banners_url
  end

  private

    def banner_params
      params.require(:banner).permit(:picture,:url)
    end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController

  before_action :authenticate_user!, only:[:index,:create,:destroy]

  def index
    @work = Work.new
    @works = Work.all
    @displayingwork = Displayingwork.first
  end

  def show
    @work = Work.find(params[:id])
  end

  def create
    @work = Work.new(work_params)
    @work.save
    callreturn
    redirect_to works_url
  end

  def destroy
    Work.find(params[:id]).destroy
    callreturn
    redirect_to works_url
  end

  private

    def update_param
      params.require(:work1).permit(:id)
    end

    def work_params
      params.require(:work).permit(:picture, :workname, :name)
    end

    def callreturn
      @work = Work.new
      @works = Work.all
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/displayingwork_helper.rb
module DisplayingworkHelper
end

app/helpers/registers_helper.rb
module RegistersHelper

  def hasTdmfile?(register)
    register.tdmfiles.count==0
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def seletedlanguage(la)
    cookies.permanent[:language]=la
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def isHome?
    request.url==root_url
  end
end

app/helpers/tdmfiles_helper.rb
module TdmfilesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/admins/filemanagement.html.erb
<h2 class="center">作品管理</h2>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h5 class="center">總件數：<%= @tdmfilecount %></h5>
    </div>
  </div>
</div>
<hr>
<div class="filetable">
  <table class="table">
    <tr style="font-weight: bolder;">
      <td></td>
      <td>作品名稱</td>
      <td>預覽圖</td>
      <td>姓名</td>
      <td>E-mail</td>
      <td>報名編號</td>
    </tr>
    <% image=0 %>
    <% @tdmfiles.each do |tdmfile| %>
      <% register=Register.find_by(:id=>tdmfile.register_id) %>
      <% if register.prohibit==false %>
        <tr>
          <td><%= link_to "刪除", tdmfile, class:"btn btn-danger btn-xs", method: :delete, data:{confirm:"確定刪除？"} %></td>
          <td><%= link_to tdmfile.igsfile.to_s.rpartition("/").last,tdmfile.igsfile.url %></td>
          <td>
            <% image+=1 %>
            <% if tdmfile.picture1.url!=nil %>
              <%= link_to (image_tag tdmfile.picture1.url, size:"30x30"),tdmfile.picture1.url,:class => "listener", :id => "#{image}image1", :target =>"_blank" %>
              <%= image_tag tdmfile.picture1.url,:class => "largeimage", :id => "#{image}image1large" %>
            <% end %>
            <% if tdmfile.picture2.url!=nil %>
              <%= link_to (image_tag tdmfile.picture2.url, size:"30x30"),tdmfile.picture2.url,:class => "listener", :id => "#{image}image2", :target =>"_blank" %>
              <%= image_tag tdmfile.picture2.url, :class => "largeimage", :id => "#{image}image2large" %>
            <% end %>
            <% if tdmfile.picture3.url!=nil %>
              <%= link_to (image_tag tdmfile.picture3.url, size:"30x30"),tdmfile.picture3.url,:class => "listener", :id => "#{image}image3", :target =>"_blank" %>
              <%= image_tag tdmfile.picture3.url, :class => "largeimage", :id => "#{image}image3large" %>
            <% end %>
          </td>
          <td><%= register.name %></td>
          <td><%= register.email %></td>
          <td><%= register.merchant_trade_no %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

<script>
  $('.listener').hover(
    function(){
      var n=$(this).attr('id')
      $('#'+n+"large").stop().animate({"opacity":"1"},"fast");
      $('#'+n+"large").css('zIndex','1')
    },
    function(){
      var n=$(this).attr('id')
      $('#'+n+"large").stop().animate({"opacity":"0"},"fast");
      $('#'+n+"large").css('zIndex','-1')
    }
  )
</script>

app/views/admins/registermanagement.html.erb
<h2 class="center">參賽者管理</h2>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h5 class="center">總報名人數：<%= @registers.count %></h5>
      <h5 class="center">今日報名人數：<%= @todayregister %></h5>
      <h5 class="center">封鎖人數：<%= @prohibitamount %></h5>
    </div>
    <div class="col-md-4">
      <h5 class="center">已繳費：<%= @paidamount %></h5>
      <h5 class="center">未繳費：<%= @unpaidamount %></h5>
      <h5 class="center">金額錯誤：<%= @erroramount %></h5>
    </div>
    <div class="col-md-4">
      <h5 class="center">總獲利：<%= @effectiveprofit+@errprprofit %></h5>
      <h5 class="center">有效獲利：<%= @effectiveprofit %></h5>
      <h5 class="center">錯誤金額：<%= @errprprofit %></h5>
    </div>
  </div>
</div>
<hr>
<div class="registerstable">
  <table class="table">
    <tr style="font-weight: bolder;">
      <td></td>
      <td>
        <form action="registermanagement" method="get">
          <% @nameorder = @nameorder || 2 %>
          <input type="hidden" name="order" value="<%= @nameorder %>"/>
          <input class="btn btn-default" type="submit" value="姓名"/>
        <% if @nameorder==1 && @nametri==true %>
          <span class="invertedtriangle"></span>
        <% elsif @nameorder==2 && @nametri==true %>
          <span class="triangle"></span>
        <% end %>
        </form>
      </td>
      <td>
        <form action="registermanagement" method="get">
          <% @emailorder = @emailorder || 4 %>
          <input type="hidden" name="order" value="<%= @emailorder %>"/>
          <input class="btn btn-default" type="submit" value="E-mail"/>
        <% if @emailorder==3 && @emailtri==true %>
          <span class="invertedtriangle"></span>
        <% elsif @emailorder==4 && @emailtri==true %>
          <span class="triangle"></span>
        <% end %>
        </form>
      </td>
      <td>報名編號</td>
      <td>報名日期</td>
      <td>
        <form action="registermanagement" method="get">
          <% @paidorder = @paidorder || 6 %>
          <input type="hidden" name="order" value="<%= @paidorder %>"/>
          <input class="btn btn-default" type="submit" value="繳費狀態"/>
        <% if @paidorder==6 && @paidtri==true %>
          <span class="invertedtriangle"></span>
        <% elsif @paidorder==5 && @paidtri==true %>
          <span class="triangle"></span>
        <% end %>
        </form>
      </td>
      <td><div class="center">繳費日期</div></td>
      <td><div class="center">繳費金額</div></td>
      <td><div class="center">繳費方式</div></td>
    </tr>
    <% @registers.each do |register| %>
      <tr>
        <td>
          <%= form_tag prohibit_path,method: :get do %>
            <%= hidden_field_tag :email, register.email %>
              <% if register.prohibit==false %>
                <%= submit_tag "封鎖", class: "btn btn-warning" %>
              <% else %>
                <%= submit_tag "解除", class: "btn btn-danger" %>
              <% end %>
          <% end %>
        </td>
        <td><%= register.name %></td>
        <td><%= register.email %></td>
        <td><%= register.merchant_trade_no %></td>
        <td><%= register.created_at.strftime("%m/%d %T") %></td>
        <% paid=register.paystatus %>
        <td>
          <div class="center" style="width:7vw; font-size:1vw; font-family:Helvetica;">
            <% if paid==3 %>
              <p class="bg-success">已付款</p>
            <% elsif paid==1%>
              <p class="bg-warning">金額錯誤</p>
            <% else %>
              <p class="bg-danger">尚未付款</p>
            <% end %>
          </div>
        </td>
        <% params=register.params %>
        <% if(paid==1 || paid == 3)%>
          <td>
            <div class="center">
              <%= params['PaymentDate'] %>
            </div>
          </td>
          <td>
            <div class="center">
              <%= params['TradeAmt'] %>
            </div>
          </td>
          <td>
            <div class="center">
              <%= params['PaymentType'] %>
            </div>
          </td>
        <% else %>
          <td><div class="center">-</div></td>
          <td><div class="center">-</div></td>
          <td><div class="center">-</div></td>
        <% end %>
        <td>
          <%= form_tag transactions_path, method: :get do %>
            <%= hidden_field_tag :email, register.email %>
            <%= submit_tag "帳單查詢", name:nil, class:"btn btn-default" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer_holder">
    <div class="footer_upcontainer">
      <div class="footer_text">
        <p>
          Copyright 2016© LINE  Design．Dream．Discover
        </p>
        <p>
          <i class="fa fa-flag"></i> Taiwan R.O.C
        </p>
        <p>
          <i class="fa fa-map-marker"></i> 台北市信義路5段5號3E47 世貿國際商辦大樓
        </p>
        <p>
          <i class="fa fa-phone"></i> 02-27295680
        </p>
        <p>
          <i class="fa fa-fax"></i> 02-27297107
        </p>
        <p>
          <i class="fa fa-envelope"></i> LINEDDD@gmail.com
        </p>
      </div>
      <div class="footer_socialicon">
        <a href="https://www.facebook.com/" target="_blank">
          <i class="fa fa-facebook"></i>
        </a>
        <a href="https://twitter.com/" target="_blank">
          <i class="fa fa-twitter"></i>
        </a>
        <a href="http://www.youtube.com/" target="_blank">
          <i class="fa fa-youtube"></i>
        </a>
        <a href="https://www.instagram.com/" target="_blank">
          <i class="fa fa-instagram"></i>
        </a>
      </div>
    </div>
    <div class="center">
      <div class="footer_img"></div>
    </div>
    <div class="footer_icon">
      <i class="fa fa-cc-visa"></i>
      <i class="fa fa-cc-mastercard"></i>
      <i class="fa fa-cc-jcb"></i>
    </div>
    <div class="languageselect">
      <%= link_to 'English',language_path(:language => "en"),:method => :post, class:"languagebutton",style:"" %>
      <%= link_to '简体中文',language_path(:language => "zh-CN"),:method => :post, class:"languagebutton",style:"" %>
      <%= link_to '繁體中文',language_path(:language => "zh-TW"),:method => :post, class:"languagebutton",style:"" %>
    </div>
  </div>
    
</footer>

<script type="text/javascript">
  <%if !isHome? %>
    $(window).bind('scroll',function(){
      $('.navbar-default').addClass('on');
    })
  <% end %>
</script>

app/views/layouts/_header.html.erb
<header id="header">
  <nav class="navbar navbar-default navbar-fixed-top top-nav-collapse 
  <% if !isHome? %>
  on
  <% end %>
  " role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-brand" id="logo">
          <a href="/">
            <img alt="Brand"/>
          </a>
        </div>
      </div>

      <div class="collapse navbar-collapse clearfix navMenu" id="bs-example-navbar-collapse-1" role="navigation" aria-expanded="true">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/declare">
            <%= t("現在報名！") %>
          </a></li>
          <li><a href="/search">
            <%= t("報名查詢") %>
          </a></li>
          <% if current_user %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                後台
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "參賽者管理", registermanagement_path %></li>
                <li><%= link_to "作品管理", filemanagement_path %></li>
                <li><%= link_to "作品上架", works_path %></li>
                <li><%= link_to "廣告上架", banners_path %></li>
                <li><%= link_to("登出", destroy_user_session_path, method: :delete) %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>3DPrintingContest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>
  <meta name="viewport" content="width=device-width,height=device-height,initial-scale=1.0,maximum-scale=1.0,user-scalable=no">
</head>
<body>
  <%= render 'layouts/header' %>
  <!-- <div class="container-fluid">
    <% flash.each do |message_type,message| %>
      <%= content_tag(:div,message,class: "alert alert-#{message_type}") %>
    <% end %>
  </div> -->
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>