config/routes.rb
Rails.application.routes.draw do

  post 'contactus' => 'static_pages#contactus'

  post  'language' => 'sessions#create'

  devise_for :users
  get 'registermanagement' => 'admins#registermanagement'
  get 'filemanagement' => 'admins#filemanagement'

  root 'static_pages#home'

  get  'info'      => 'static_pages#info'
  get  'declare'   => 'static_pages#declare'
  get  'search'    => 'static_pages#search'
  get  'form'      => 'static_pages#form'

  get 'prohibit' => 'registers#prohibit'

  get 'allpayform' => 'static_pages#allpayform'

  post 'notify', to: 'static_pages#notify', as: 'notify'

  get "static_pages/check_email", :controller => "static_pages", :action => "check_email"
  resources :transactions, only: :index
  resources :registers
  resources :tdmfiles,     only: [:create,:destroy]
  resources :works,        only: [:index,:show,:create,:destroy]
  resources :displayingwork, only: :update
  resources :banners, only: [:index,:update]

end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :displayingwork
  mount_uploader :picture, PictureUploader
  validates :picture, presence: true
  validates :name, presence: true
  validates :workname, presence: true
end

app/controllers/works_controller.rb
class WorksController < ApplicationController

  before_action :authenticate_user!, only:[:index,:create,:destroy]

  def index
    @work = Work.new
    @works = Work.all
    @displayingwork = Displayingwork.first
  end

  def show
    @work = Work.find(params[:id])
  end

  def create
    @work = Work.new(work_params)
    @work.save
    callreturn
    redirect_to works_url
  end

  def destroy
    Work.find(params[:id]).destroy
    callreturn
    redirect_to works_url
  end

  private

    def update_param
      params.require(:work1).permit(:id)
    end

    def work_params
      params.require(:work).permit(:picture, :workname, :name)
    end

    def callreturn
      @work = Work.new
      @works = Work.all
    end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/index.html.erb
<h2 class="center">作品上架</h2>
<br>
<p>前台在不同視窗寬度下的排列方式</p>
<p>白底為可上架之區域</p>
<p>分別為欄位1~6</p>
<p>若要上架作品，請先新增待上架作品</p>
<p>再於欄位中輸入欲上架作品之作品編號</p>
<img src="assets/workdemo<768.png">
<img src="assets/workdemo>768<992.png">
<img src="assets/workdemo>992.png">
<div class="container worksindex">
  <div class="row">
    <div class="col-md-3">
      <%= form_for @displayingwork, method: :patch do |f|%>
        <%= f.label :col1, "欄位1 作品編號" %>
        <%= f.text_field :col1, class: 'form-control' %>
        <%= f.label :col2, "欄位2 作品編號" %>
        <%= f.text_field :col2, class: 'form-control' %>
        <%= f.label :col3, "欄位3 作品編號" %>
        <%= f.text_field :col3, class: 'form-control' %>
        <%= f.label :col4, "欄位4 作品編號" %>
        <%= f.text_field :col4, class: 'form-control' %>
        <%= f.label :col5, "欄位5 作品編號" %>
        <%= f.text_field :col5, class: 'form-control' %>
        <%= f.label :col6, "欄位6 作品編號" %>
        <%= f.text_field :col6, class: 'form-control' %>
        <%= f.submit "上架", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col-md-3"></div>
    <br>
    <br>
    <br>
    <div class="col-md-3">
      <%= form_for(@work, html:{multipart: true}) do |f| %>
        <%= f.file_field :picture %>
        <%= f.text_field :workname, placeholder: "作品名稱", class: 'form-control' %>
        <%= f.text_field :name, placeholder: "姓名", class: 'form-control' %>
        <%= f.submit "新增待上架作品", class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
  <h2 class="center">待上架作品</h2>
  <br>
  <div class="row">
    <div class="col-md-12">
      <table class="table" style="max-width: 1000px">
        <tr style="font-weight: bolder;">
          <td>作品編號</td>
          <td>作品圖片</td>
          <td>作品名稱</td>
          <td>姓名</td>
        </tr>
        <% image=0 %>
        <% @works.each do |work| %>
          <% image+=1 %>
          <tr>
            <td><%= work.id %></td>
            <td>
              <%= link_to (image_tag work.picture.url, size:"30x30"),work.picture.url,:class => "listener", :id => "#{image}image1", :target =>"_blank" %>
              <%= image_tag work.picture.url,:class => "largeimage", :id => "#{image}image1large" %>
            </td>
            <td><%= link_to work.workname, work_path(work.id) %></td>
            <td><%= work.name %></td>
            <td>
              <% if @displayingwork.works.find_by(id:work.id) %>
                <% number||=1 if @displayingwork.col1==work.id %>
                <% number||=2 if @displayingwork.col2==work.id %>
                <% number||=3 if @displayingwork.col3==work.id %>
                <% number||=4 if @displayingwork.col4==work.id %>
                <% number||=5 if @displayingwork.col5==work.id %>
                <% number||=6 if @displayingwork.col6==work.id %>
                上架中欄位<%= number %>
              <% else %>
                <%= link_to "刪除", work, method: :delete, data:{confirm:"確定刪除？"} %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>
<script>
  $('.listener').hover(
    function(){
      var n=$(this).attr('id')
      $('#'+n+"large").stop().animate({"opacity":"1"},"fast");
      $('#'+n+"large").css('zIndex','1')
    },
    function(){
      var n=$(this).attr('id')
      $('#'+n+"large").stop().animate({"opacity":"0"},"fast");
      $('#'+n+"large").css('zIndex','-1')
    }
  )
</script>

app/views/works/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12" style="font-family: Microsoft JhengHei;">
      <div class="thumbnail">
        <img src="<%= @work.picture %>" data-src="holder.js/100%x180"/>
        <div class="center">
          <h3><%= t("作品名稱") %> ： <%= @work.workname %></h3>
          <p><%= t("參賽者") %> ： <%= @work.name %></p>
          <br>
          <div id="fb-root"></div>
          <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.5";
            fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));</script>
          <div class="fb-share-button" data-href="http://tdpcontest.herokuapp.com<%= work_path(@work.id) %>" data-layout="button_count"></div>
        </div>
      </div>
    </div>
  </div>
</div>